# Generated by Django 3.1.2 on 2021-02-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb_url',
            field=models.URLField(null=True),
        ),
    ]
