# Generated by Django 3.1.2 on 2021-02-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_thumb_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
